# Generated by Django 5.2.3 on 2025-06-16 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="menu",
            options={"verbose_name": "Меню"},
        ),
        migrations.AlterModelOptions(
            name="menuitem",
            options={
                "ordering": ["order"],
                "verbose_name": "Пункт меню",
                "verbose_name_plural": "Пункты меню",
            },
        ),
    ]
