# Generated by Django 5.2.3 on 2025-06-16 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0002_alter_menu_options_alter_menuitem_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="menu",
            options={"verbose_name": "Меню", "verbose_name_plural": "Меню"},
        ),
    ]
